name: Exam Autograde

on:
  push:
  pull_request:

jobs:
  autograde:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: Build
      run: cargo build --release
    - name: Run and validate output
      run: |
        output=$(cargo run --release)
        if [ "$output" != "Hello, World!" ]; then
          echo "❌ 输出错误，应该为：Hello, World!"
          exit 1
        else
          echo "✅ 恭喜，输出正确！"
        fi
